version: '3'

services:
  fastapi_service:
    build:
      context: ./fastapi_service
    ports:
      - "8000:80"
    depends_on:
      - consul
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - SERVICE_NAME=fastapi_service
      - SERVICE_PORT=80
    restart: "unless-stopped"
    command: ["sh", "-c", "python main.py"]  # Cambiato il comando di avvio
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/health"]
      interval: 1s
      timeout: 3s
      retries: 30


  consul:
    image: consul:1.10.3
    ports:
      - "8500:8500"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8500/v1/status/leader"]
      interval: 1s
      timeout: 3s
      retries: 3
  nginx:
    build: ./nginx
    ports:
      - "8081:8081"
    depends_on:
      - consul
      - fastapi_service    