version: "3.8"

services:
  user_management_service:
    image: user_management_service_image
    # Configurazioni specifiche per il tuo microservizio
    depends_on:
      - kafka
      - consul
      - eureka
      - postgres
      - gateway  # Aggiunto il servizio gateway come dipendenza

      # Aggiungi altre dipendenze, se necessario

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper

  consul:
    image: consul
    ports:
      - "8500:8500"

  eureka:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    depends_on:
      - consul

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
