version: '3'

services:
  ms_commenti:
    build:
      context: ./ms_commenti
    ports:
      - "8003:8003"
    depends_on:
      - security_service
      - kafka
    environment:
      - AUTH_MICROSERVICE_URL=http://security_service:8500
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # Aggiungi altre configurazioni Kafka necessarie per il tuo microservizio

  security_service:
    build:
      context: ./security_service
    ports:
      - "8500:8500"
  
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSERISCI_IL_TUO_IP:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSERISCI_IL_TUO_IP:PLAINTEXT
      KAFKA_ADVERTISED_LISTENER: INSERISCI_IL_TUO_IP:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
