version: '3'

services:
  ms_gestione_prodotti:
    build:
      context: ./ms_gestione_prodotti
    ports:
      - "8006:8006"
    depends_on:
      - kafka
      - eureka

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSERISCI_IL_TUO_IP:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSERISCI_IL_TUO_IP:PLAINTEXT
      KAFKA_ADVERTISED_LISTENER: INSERISCI_IL_TUO_IP:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
