# nginx/Dockerfile
FROM nginx:latest

# Copia il file di configurazione di Nginx nella directory corretta
COPY nginx.conf /etc/nginx/nginx.conf

# Rimuovi la configurazione di default di Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Esponi la porta 8081
EXPOSE 8081
