        # Cambiato il percorso per puntare alla directory corrente , mentre il./ sottodirectory

version: "3.8"

services:
  user_management_service:
    build:
      context: .  # Cambiato il percorso per puntare alla directory corrente , mentre il./ sottodirectory
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
