# Usa l'immagine di Python 3.9 come base
FROM python:3.9

# Imposta la directory di lavoro nel contenitore
WORKDIR /app

# Copia il tuo codice nell'immagine
COPY . /app

# Installa le dipendenze del tuo progetto
RUN pip install -r requirements.txt

# Espone la porta 8000
EXPOSE 8000

# Comando per avviare il tuo servizio quando il contenitore è in esecuzione
CMD ["python", "main.py"]
